# Generated by Django 3.1.6 on 2021-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num',
            name='age',
        ),
        migrations.AddField(
            model_name='num',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='num',
            name='is_pro',
            field=models.BooleanField(default=True),
        ),
    ]
