# Generated by Django 3.1.6 on 2021-02-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210214_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Num',
        ),
    ]
