# Generated by Django 3.1.6 on 2021-02-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['publish_date']},
        ),
    ]
